//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace WebSpider.Objects.AdiExport
{
    public partial class ADI_Inventory
    {
        public long ID { get; set; }
        public string PART_NUM { get; set; }
        public int? TotalInventory { get; set; }
        public int? Dallas { get; set; }
        public int? DC_AtlantaHub { get; set; }
        public int? DC_Dallas_Hub { get; set; }
        public int? DC_Elk_Grove_Hub { get; set; }
        public int? DC_Feura_Bush { get; set; }
        public int? DC_Louisville_Hub { get; set; }
        public int? DC_Reno_Hub { get; set; }
        public int? DC_Richmond_Dist_Ctr { get; set; }
        public int? Oklahama { get; set; }
        public int? RemainingBranches { get; set; }
        public DateTime? LastUpdate { get; set; }
    }
}
